# Generated by Django 2.0.3 on 2018-04-03 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_auto_20180402_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
